name: PR File Changes
on:
    pull_request:
      branches:
        - master  # Only run on PRs targeting master
jobs:
  track-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          # Get the base and head commits
          BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          
          echo "Deleted files:"
          git diff --name-status $BASE_SHA $HEAD_SHA | grep '^D' | cut -f2- | while read -r file; do
            echo "  - $file"
          done
          
          echo -e "\nRenamed files:"
          git diff --name-status $BASE_SHA $HEAD_SHA | grep '^R' | while read -r status old new; do
            echo "  - $old -> $new"
          done