name: Check Documentation Changes

on:
  pull_request:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diff

      - name: Get base and head commits
        run: |
          BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          
          # Detect deleted files
          DELETED_FILES=$(git diff --name-status $BASE_SHA $HEAD_SHA | grep '^D' | cut -f2-)
          echo "DELETED_FILES<<EOF" >> $GITHUB_ENV
          echo "$DELETED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Detect renamed files
          RENAMED_FILES=$(git diff --name-status $BASE_SHA $HEAD_SHA | grep '^R' | while read -r status old new; do
            echo "$old -> $new"
          done)
          echo "RENAMED_FILES<<EOF" >> $GITHUB_ENV
          echo "$RENAMED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


          # Set the warning flag if there are deleted or renamed files
          if [[ -n "$DELETED_FILES" || -n "$RENAMED_FILES" ]]; then
            echo "warning=true" >> $GITHUB_ENV
          fi

  post-warning:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.warning == 'true'

    steps:
      - name: Post PR warning if necessary
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const repo = context.repo;
            const deletedFiles = `${process.env.DELETED_FILES}`.trim();
            const renamedFiles = `${process.env.RENAMED_FILES}`.trim();

            let message = `⚠️ **Documentation Warning**\n\n`;
            if (deletedFiles) {
              message += `**Deleted files:**\n\`\`\`\n${deletedFiles}\n\`\`\`\n\n`;
            }
            if (renamedFiles) {
              message += `**Renamed files:**\n\`\`\`\n${renamedFiles}\n\`\`\`\n\n`;
            }

            message += `Please verify these changes before merging.`;

            github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issue_number,
              body: message
            });
