name: Check Documentation Changes

on:
  pull_request:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get base commit of the PR
        run: |
          echo "BASE_COMMIT=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

      - name: Identify deleted and renamed files
        run: |
          BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          
          echo "Deleted files:"
          DELETED_FILES=$(git diff --name-status $BASE_SHA $HEAD_SHA | grep '^D' | cut -f2-)
          if [[ -n "$DELETED_FILES" ]]; then
            echo "$DELETED_FILES"
          fi
          
          echo -e "\nRenamed files:"
          RENAMED_FILES=$(git diff --name-status $BASE_SHA $HEAD_SHA | grep '^R' | while read -r status old new; do
            echo "$old -> $new"
          done)
          if [[ -n "$RENAMED_FILES" ]]; then
            echo "$RENAMED_FILES"
          fi

          # Set the warning flag if there are deleted or renamed files
          if [[ -n "$DELETED_FILES" || -n "$RENAMED_FILES" ]]; then
            echo "warning=true" >> $GITHUB_ENV
          fi

      - name: Post PR warning if necessary
        if: env.warning == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const repo = context.repo;
            const deletedFiles = `${process.env.DELETED_FILES}`.trim();
            const renamedFiles = `${process.env.RENAMED_FILES}`.trim();

            let message = `⚠️ **Documentation Warning**\n\n`;
            if (deletedFiles) {
              message += `**Deleted files:**\n\`\`\`\n${deletedFiles}\n\`\`\`\n\n`;
            }
            if (renamedFiles) {
              message += `**Renamed files (content match or Git detected):**\n\`\`\`\n${renamedFiles}\n\`\`\`\n\n`;
            }

            message += `Please verify these changes before merging.`;

            github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issue_number,
              body: message
            });
